### ISSUE TITLE
NetworkActiveKnowledgeBase not found

### ISSUE THREAD

**Issue by Tusaka** [gbossert/pylstar#3]
Hello, I am learning about protocol reverse engineering, thanks for your Opening source it's great! I have been learning your project for a long time. And there is one problem, when i tried to use pylstar followed the 'readme', it showed me that 'No module named pylstar.NetworkActiveKnowledgeBase', actually , i haven't found it in the source code, did you lose it?

**Comment by gbossert** [comment]
Sorry for the delay. I've restored this file from the git log and pushed it in the next branch (see commit https://github.com/gbossert/pylstar/commit/1fd9857ec79e4f23feb7891da343297923d02c25).
