### ISSUE TITLE
CoffeeMachineInferer.py example is not running

### ISSUE THREAD

**Issue by roiDaniela** [gbossert/pylstar#4]
Hello, 
I'm running the "next" branch,
but I get error:
Exception: Query 'OutputQuery(I = [Letter('REFILL_WATER')], O = None)' could not be queried

tnx
![coffee1](https://user-images.githubusercontent.com/11479074/68547186-88ba0b00-03d6-11ea-8da2-e640d031a6c0.PNG)
![coffee2](https://user-images.githubusercontent.com/11479074/68547187-88ba0b00-03d6-11ea-8f59-3f46429a2f40.PNG)

Also when running the test as you described in the readme I get error
python setup.py test

@gbossert

**Comment by roiDaniela** [comment]
Also when running the test as you described in the readme I get error
python setup.py test

**Comment by roiDaniela** [comment]
@gbossert

**Comment by gbossert** [comment]
Hello,

This exception occurs when the inferer cannot communicate with the target. In this specific case, the target is started by the test script (see https://github.com/gbossert/pylstar/blob/next/test/src/test_pylstar/coffee_machine_example/CoffeeMachineInferer.py#L22). If for any reason, this command fails it will raise an exception when firing an output query.

I've checked again this test script and it worked well on my computer under the following commands:
* checkout out the `next` branch: `git pull origin next`
* create a virtualenv to isolate my computer libs: ` virtualenv venv`
* source my fresh virtual env: `source venv/bin/activate`
* install pylstar in devel mode: `python setup.py develop`
* this test script must be executed from its directory: `cd test/src/test_pylstar/coffee_machine_example`
* start the test script `python CoffeeMachineInferer.py 1`
* convert the produced DOT automate in png: `dot -T png coffee_machine_1.dot > coffee1.png`
* display the produced automate: `eog coffee1.png`

Does it help ?

**Comment by roiDaniela** [comment]
I'm sorry @gbossert , but it didn't help.
I have windows so instead of the commands
- source my fresh virtual env: source venv/bin/activate
- install pylstar in devel mode: python setup.py develop

I used 
- pip install virtualenv
- virtualenv env
- .../Scripts/activate.bat

I still get the below error
<img width="453" alt="cofee3" src="https://user-images.githubusercontent.com/11479074/68618685-91900700-04d2-11ea-83e1-d6639aaab4d7.PNG">

**Comment by roiDaniela** [comment]
@gbossert I tried with linux machine and it worked.
So, I guess that the problem was with my windows environment.
Thanks

**Comment by arpan-vs** [comment]
@roiDaniela , How you have resolve the above issue?
Because, I have also tried on the both environment to reproduce the result of CoffeeMachineInferer.py. But I am still getting the above error.
